name: AutoRelease
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: 'BedrockModerationTools'
        type: 'zip'
        filename: 'BedrockModerationTools.mcpack'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
    - uses: ncipollo/release-action@v1
      with:
          artifacts: 'BedrockModerationTools.mcpack'
          token: ${{ secrets.GITHUB_TOKEN }}


