name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with: 
          directory: 'BedrockModerationTools'
          type: 'zip'
          filename: 'BedrockModerationTools.mcpack'
          exclusions: '*.git*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

