name: AutoRelease
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: 'BedrockModerationTools'
        type: 'zip'
        filename: 'BedrockModerationTools.mcpack'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


